language: python
install:
  - pip install git+https://github.com/PyCQA/baron
  - pip install pytest
  - find . -name '*.pyc' -delete
  - python setup.py install
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
script:
  - py.test tests
  - bash ./test_doc.sh
  - pip install pygments
  - py.test tests
  - bash ./test_doc.sh